/*!
 * PoHVerifier — On-chain Groth16 Proof-of-Humanity verifier.
 *
 * Verifies zero-knowledge membership proofs generated by the poh.circom circuit
 * (Groth16 on BN254) using Arkworks (ark-groth16 + ark-bn254) in a no_std
 * Soroban environment.
 *
 * ## Protocol
 *
 * 1. The PoH oracle builds an identity Merkle tree (Poseidon hashes).
 *    Each leaf = Poseidon(identitySecret). The root is stored in `Lockb0x`.
 * 2. A user generates a Groth16 proof off-chain (via @nodezero/zk-crypto):
 *    - Proves: H(identitySecret) is a leaf in the tree with the given root
 *    - Proves: nullifier = Poseidon(identitySecret, scope)
 *    - Public outputs: root, nullifier, scope
 * 3. The user calls `PoHVerifier::verify_poh` with:
 *    - 256-byte proof (pi_a || pi_b || pi_c, BN254)
 *    - 32-byte root  (must match Lockb0x.get_state_root())
 *    - 32-byte nullifier
 *    - 32-byte scope
 * 4. The contract:
 *    a. Checks the nullifier has not been spent.
 *    b. Deserializes the Groth16 verification key (stored at init time).
 *    c. Runs the Groth16 pairing check (BN254).
 *    d. Records the nullifier on success.
 *    e. Emits a `poh_ok` event.
 *
 * ## Proof byte layout (256 bytes)
 *   [0..64]    pi_a : G1 affine — x(32) || y(32)
 *   [64..192]  pi_b : G2 affine — x0(32) || x1(32) || y0(32) || y1(32)
 *   [192..256] pi_c : G1 affine — x(32) || y(32)
 *
 * ## Public signals byte layout (3 × 32 bytes)
 *   root      : 32-byte big-endian Poseidon Merkle root
 *   nullifier : 32-byte big-endian Poseidon nullifier
 *   scope     : 32-byte big-endian domain separator
 */

use alloc::vec::Vec;

use ark_bn254::{Bn254, Fq, Fq2, Fr, G1Affine, G2Affine};
use ark_ff::PrimeField;
use ark_groth16::{Groth16, Proof, VerifyingKey};
use ark_snark::SNARK;
use ark_serialize::CanonicalDeserialize;
use soroban_sdk::{contract, contractimpl, contracttype, symbol_short, Address, Bytes, BytesN, Env};

// ─── Storage keys ─────────────────────────────────────────────────────────────

#[contracttype]
pub enum PoHKey {
    /// Serialised Groth16 PreparedVerifyingKey (BN254).
    VerifyingKey,
    /// Nullifier → true when the nullifier has been spent.
    Nullifier(BytesN<32>),
}

// ─── Helper: deserialize a 32-byte big-endian field element ──────────────────

fn bytes32_to_fr(b: &[u8; 32]) -> Fr {
    Fr::from_be_bytes_mod_order(b)
}

fn bytes32_to_fq(b: &[u8; 32]) -> Fq {
    Fq::from_be_bytes_mod_order(b)
}

/// Deserialize a G1 affine point from 64 bytes (x || y, each 32-byte BE).
fn g1_from_bytes(data: &[u8]) -> G1Affine {
    assert!(data.len() == 64, "G1 point must be 64 bytes");
    let x = bytes32_to_fq(data[0..32].try_into().expect("x slice"));
    let y = bytes32_to_fq(data[32..64].try_into().expect("y slice"));
    G1Affine::new(x, y)
}

/// Deserialize a G2 affine point from 128 bytes (x0 || x1 || y0 || y1).
fn g2_from_bytes(data: &[u8]) -> G2Affine {
    assert!(data.len() == 128, "G2 point must be 128 bytes");
    let x0 = bytes32_to_fq(data[0..32].try_into().expect("x0"));
    let x1 = bytes32_to_fq(data[32..64].try_into().expect("x1"));
    let y0 = bytes32_to_fq(data[64..96].try_into().expect("y0"));
    let y1 = bytes32_to_fq(data[96..128].try_into().expect("y1"));
    G2Affine::new(Fq2::new(x0, x1), Fq2::new(y0, y1))
}

/// Deserialize a 256-byte proof blob into an ark-groth16 `Proof<Bn254>`.
fn deserialize_proof(proof_bytes: &[u8; 256]) -> Proof<Bn254> {
    let a = g1_from_bytes(&proof_bytes[0..64]);
    let b = g2_from_bytes(&proof_bytes[64..192]);
    let c = g1_from_bytes(&proof_bytes[192..256]);
    Proof { a, b, c }
}

// ─── PoHVerifier contract ─────────────────────────────────────────────────────

#[contract]
pub struct PoHVerifier;

#[contractimpl]
impl PoHVerifier {
    /// One-time initialisation. Stores the Groth16 verification key.
    ///
    /// # Arguments
    /// * `operator` — The operator `Address` (auth-gated init).
    /// * `vk_bytes` — Canonical-serialised `VerifyingKey<Bn254>` produced by
    ///   `snarkjs zkey export verificationkey … | node vk_to_bytes.mjs`.
    pub fn init_verifier(env: Env, operator: Address, vk_bytes: Bytes) {
        operator.require_auth();
        assert!(
            !env.storage().persistent().has(&PoHKey::VerifyingKey),
            "PoHVerifier: already initialized"
        );
        env.storage().persistent().set(&PoHKey::VerifyingKey, &vk_bytes);
    }

    /// Verifies a Groth16 Proof of Humanity and records the nullifier.
    ///
    /// # Arguments
    /// * `proof_bytes` — 256-byte proof (pi_a‖pi_b‖pi_c on BN254).
    /// * `root`        — 32-byte Merkle root (must match Lockb0x).
    /// * `nullifier`   — 32-byte nullifier = Poseidon(identitySecret, scope).
    /// * `scope`       — 32-byte domain separator.
    ///
    /// Returns `true` on success. Panics on invalid proof, spent nullifier,
    /// or contract not initialized.
    pub fn verify_poh(
        env: Env,
        proof_bytes: Bytes,
        root: BytesN<32>,
        nullifier: BytesN<32>,
        scope: BytesN<32>,
    ) -> bool {
        // 1. Replay protection — reject spent nullifiers
        assert!(
            !env.storage().persistent().has(&PoHKey::Nullifier(nullifier.clone())),
            "PoHVerifier: nullifier already spent"
        );

        // 2. Load and deserialize the stored verification key
        let vk_bytes: Bytes = env
            .storage()
            .persistent()
            .get(&PoHKey::VerifyingKey)
            .expect("PoHVerifier: not initialized");

        let vk_slice = vk_bytes.to_alloc_vec();
        let vk = VerifyingKey::<Bn254>::deserialize_compressed(vk_slice.as_slice())
            .expect("PoHVerifier: invalid verification key");
        let pvk = Groth16::<Bn254>::process_vk(&vk).expect("PoHVerifier: vk processing failed");

        // 3. Deserialize the 256-byte proof
        assert!(proof_bytes.len() == 256, "PoHVerifier: proof must be 256 bytes");
        let proof_arr: [u8; 256] = proof_bytes
            .to_alloc_vec()
            .try_into()
            .expect("PoHVerifier: proof length mismatch");
        let proof = deserialize_proof(&proof_arr);

        // 4. Build public inputs: [root, nullifier, scope] as BN254 field elements
        let root_fe = bytes32_to_fr(&root.to_array());
        let null_fe = bytes32_to_fr(&nullifier.to_array());
        let scope_fe = bytes32_to_fr(&scope.to_array());
        let public_inputs: Vec<Fr> = alloc::vec![root_fe, null_fe, scope_fe];

        // 5. Groth16 pairing-based verification (the ZK part)
        let valid = Groth16::<Bn254>::verify_with_processed_vk(&pvk, &public_inputs, &proof)
            .expect("PoHVerifier: verification error");
        assert!(valid, "PoHVerifier: proof invalid");

        // 6. Record nullifier as spent
        env.storage()
            .persistent()
            .set(&PoHKey::Nullifier(nullifier.clone()), &true);

        // 7. Emit verification event (root, nullifier indexed)
        env.events().publish((symbol_short!("poh_ok"),), (root, nullifier));

        true
    }

    /// Returns true if the given nullifier has already been spent.
    pub fn is_nullifier_used(env: Env, nullifier: BytesN<32>) -> bool {
        env.storage().persistent().has(&PoHKey::Nullifier(nullifier))
    }
}

// Provide a helper on Bytes to convert to an alloc Vec without heap leaking.
trait BytesToVec {
    fn to_alloc_vec(&self) -> Vec<u8>;
}

impl BytesToVec for Bytes {
    fn to_alloc_vec(&self) -> Vec<u8> {
        let len = self.len() as usize;
        let mut v = Vec::with_capacity(len);
        for i in 0..len {
            v.push(self.get(i as u32).unwrap());
        }
        v
    }
}

// ─── PoHVerifier tests ────────────────────────────────────────────────────────

#[cfg(test)]
mod poh_tests {
    use super::*;
    use soroban_sdk::{testutils::Address as _, Bytes, BytesN, Env};

    /// Generates a trivially-invalid 256-byte proof (all zeros) for testing
    /// initialization and nullifier logic (not proof correctness).
    fn zero_proof(env: &Env) -> Bytes {
        let zeros = [0u8; 256];
        Bytes::from_slice(env, &zeros)
    }

    fn zero_bytes32(env: &Env) -> BytesN<32> {
        BytesN::from_array(env, &[0u8; 32])
    }

    #[test]
    fn test_poh_verifier_rejects_double_spend() {
        let env = Env::default();
        env.mock_all_auths();

        let contract_id = env.register_contract(None, PoHVerifier);
        let client = PoHVerifierClient::new(&env, &contract_id);

        // Use a minimal-size vk for testing initialization only.
        // In production this is replaced with the real Groth16 vk bytes.
        // We test double-spend detection, which runs BEFORE proof verification.
        let operator = Address::generate(&env);
        let vk_placeholder = Bytes::from_slice(&env, &[0u8; 32]); // placeholder
        client.init_verifier(&operator, &vk_placeholder);

        // Mark a nullifier as spent by directly setting storage
        let nullifier = zero_bytes32(&env);
        env.storage()
            .persistent()
            .set(&PoHKey::Nullifier(nullifier.clone()), &true);

        // A second attempt with the same nullifier must panic
        let result = std::panic::catch_unwind(|| {
            client.verify_poh(
                &zero_proof(&env),
                &zero_bytes32(&env),
                &nullifier,
                &zero_bytes32(&env),
            )
        });
        assert!(result.is_err(), "Expected panic on double-spend");
    }

    #[test]
    fn test_is_nullifier_used_returns_false_for_fresh() {
        let env = Env::default();
        env.mock_all_auths();

        let contract_id = env.register_contract(None, PoHVerifier);
        let client = PoHVerifierClient::new(&env, &contract_id);

        let nullifier = zero_bytes32(&env);
        assert!(!client.is_nullifier_used(&nullifier));
    }

    #[test]
    #[should_panic(expected = "PoHVerifier: already initialized")]
    fn test_double_initialize_panics() {
        let env = Env::default();
        env.mock_all_auths();

        let contract_id = env.register_contract(None, PoHVerifier);
        let client = PoHVerifierClient::new(&env, &contract_id);

        let operator = Address::generate(&env);
        let vk = Bytes::from_slice(&env, &[0u8; 32]);
        client.init_verifier(&operator, &vk);
        client.init_verifier(&operator, &vk); // must panic
    }
}
