pragma circom 2.1.6;

/*
 * nullifier.circom – Nullifier Generation Circuit
 *
 * Purpose
 * -------
 * Generates a cryptographic nullifier that can be published on-chain to
 * prevent double-spending / spamming WITHOUT revealing the underlying user
 * identity.
 *
 * A nullifier is a deterministic, one-way hash of the user's private identity
 * secret combined with a public scope (e.g. a post ID or time bucket).  The
 * same user will always produce the same nullifier for the same scope, making
 * double-use detectable.  But the nullifier reveals NOTHING about the user.
 *
 * Construction
 * ------------
 *   nullifier = Poseidon(identitySecret, scope)
 *
 * The prover also proves membership in the humanity Merkle tree (via the PoH
 * circuit) so the verifier can be confident the nullifier was generated by a
 * real human.
 *
 * Public  inputs:  nullifier, root, scope
 * Private inputs:  identitySecret, pathElements, pathIndices
 *
 * Dependencies
 * ------------
 * circomlib must be in the include path.
 */

include "node_modules/circomlib/circuits/poseidon.circom";
include "node_modules/circomlib/circuits/mux1.circom";

/*
 * Re-use the Merkle inclusion proof logic from poh.circom.
 * (In a real project this would be imported; duplicated here for clarity.)
 */
template MerkleTreeInclusionProofNullifier(levels) {
    signal input leaf;
    signal input pathElements[levels];
    signal input pathIndices[levels];
    signal output root;

    component hashers[levels];
    component muxLeft[levels];
    component muxRight[levels];

    signal levelHashes[levels + 1];
    levelHashes[0] <== leaf;

    for (var i = 0; i < levels; i++) {
        muxLeft[i]  = Mux1();
        muxRight[i] = Mux1();

        muxLeft[i].c[0]  <== levelHashes[i];
        muxLeft[i].c[1]  <== pathElements[i];
        muxLeft[i].s     <== pathIndices[i];

        muxRight[i].c[0] <== pathElements[i];
        muxRight[i].c[1] <== levelHashes[i];
        muxRight[i].s    <== pathIndices[i];

        hashers[i] = Poseidon(2);
        hashers[i].inputs[0] <== muxLeft[i].out;
        hashers[i].inputs[1] <== muxRight[i].out;

        levelHashes[i + 1] <== hashers[i].out;
    }

    root <== levelHashes[levels];
}

/*
 * NullifierCircuit (top-level circuit)
 *
 * Public  inputs: nullifier, root, scope
 * Private inputs: identitySecret, leaf, pathElements, pathIndices
 */
template NullifierCircuit(levels) {
    // ── Public inputs ──────────────────────────────────────────────────────
    // The published nullifier (prevents double-use of this scope by this user).
    signal input nullifier;

    // The on-chain Merkle root from Lockb0x.
    signal input root;

    // A public domain separator: e.g. H(postId) or H(dayBucket).
    signal input scope;

    // ── Private inputs ─────────────────────────────────────────────────────
    // The user's private identity secret (never revealed).
    signal input identitySecret;

    // The user's identity commitment leaf: H(identitySecret)
    signal input leaf;

    // Merkle authentication path.
    signal input pathElements[levels];
    signal input pathIndices[levels];

    // ── Constraint 1: verify nullifier = Poseidon(identitySecret, scope) ──
    component nullifierHasher = Poseidon(2);
    nullifierHasher.inputs[0] <== identitySecret;
    nullifierHasher.inputs[1] <== scope;
    nullifier === nullifierHasher.out;

    // ── Constraint 2: verify leaf = Poseidon(identitySecret) ──────────────
    component leafHasher = Poseidon(1);
    leafHasher.inputs[0] <== identitySecret;
    leaf === leafHasher.out;

    // ── Constraint 3: verify Merkle inclusion ─────────────────────────────
    component inclusionProof = MerkleTreeInclusionProofNullifier(levels);
    inclusionProof.leaf         <== leaf;
    inclusionProof.pathElements <== pathElements;
    inclusionProof.pathIndices  <== pathIndices;

    root === inclusionProof.root;
}

// Instantiate with a 20-level tree (matching the PoH circuit).
component main { public [nullifier, root, scope] } = NullifierCircuit(20);
